import { UIProvider } from "../types";
export const allProviders: UIProvider[] = 
[
    { id: 'chatgpt',
        provider: 'openai',
        model: 'gpt-4o-2024-11-20',
        name: 'ChatGPT 4o',
        subtext: 'Intelligent model',
        enabled: true,
        apiKey: process.env.VITE_OPENAI_API_KEY || "x",
        maxTokens: 128000,
        useTool: false },
    { id: 'chatgpt-o1', 
        provider: 'openai',
        model: 'o1-2024-12-17',
        name: 'ChatGPT o1',
        subtext: 'Advanced reasoning model',
        enabled: false,
        apiKey: process.env.VITE_OPENAI_API_KEY || "x",
        maxTokens: 128000 ,
        useTool: false },
    { id: 'anthropic35',
        provider: 'anthropic',
        model: 'claude-3-5-sonnet-20241022',
        name: 'Anthropic 3.5 Sonnet',
        subtext: 'Intelligent model',
        enabled: false,
        apiKey: process.env.VITE_ANTHROPIC_API_KEY || "x",
        maxTokens: 200000 ,
        useTool: false },
    { id: 'anthropic37',
        provider: 'anthropic',
        model: 'claude-3-7-sonnet-20250219',
        name: 'Anthropic 3.7 Sonnet',
        subtext: 'Hybrid reasoning model',
        enabled: false,
        apiKey: process.env.VITE_ANTHROPIC_API_KEY || "x",
        maxTokens: 200000 ,
        useTool: false },
    { id: 'anthropic_with_example35',
        provider: 'anthropic',
        model: 'claude-3-5-sonnet-20241022',
        name: 'Anthropic 3.5 Sonnet for Memos',
        subtext: 'Intelligent model',
        enabled: false,
        apiKey: process.env.VITE_ANTHROPIC_API_KEY || "x",
        maxTokens: 200000 ,
        useTool: true },
    { id: 'anthropic_with_example37',
        provider: 'anthropic',
        model: 'claude-3-7-sonnet-20250219',
        name: 'Anthropic 3.7 Sonnet for Memos',
        subtext: 'Hybrid reasoning model',
        enabled: false,
        apiKey: process.env.VITE_ANTHROPIC_API_KEY || "x",
        maxTokens: 200000 ,
        useTool: true }    
];
